version: '3'
services:

  redis:
    container_name: redis_container
    image: redis
    ports:
      - "6379:6379"

  web:
    build: .
    container_name: web_container
    depends_on:
      - redis
    ports:
      - "8000:8000"
    command: > 
      bash -c "
      ls && 
      python3 manage.py makemigrations blog &&
      python3 manage.py migrate && 
      python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/app
